version: '2'
services:
 docker-log:
   build: .
   command: entrypoint.sh
   ports:
    - "5000:5000"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker/containers:/var/lib/docker/containers